### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by mayankamencherla** [razorpay/razorpay-quick-payments#2]
Idea for future: Make these 2 statements configurable as a global option in the plugin config.

success_message: "Thank you for shopping with us.... {{payment_id}}"
failure_message   : "Payment failed..."

**Comment by Mayur-Wadpalliwar** [comment]
ref: #sk-enchanted-frog

**Comment by tessie** [comment]
@mayankamencherla  This does not have sprint assigned to it   cc @sunnyagg

**Comment by AbhishekRanjane** [comment]
Hi,

Is there any way I could edit the success message which appears as "Thank you for shopping with us.."
![whatsapp image 2018-12-19 at 12 34 44 am](https://user-images.githubusercontent.com/45978322/50176644-f58f6700-0325-11e9-81b9-aab1234fab29.jpeg)

**Comment by ChetanGN** [comment]
@AbhishekRanjane as of now there is no flexibility to edit the message from plugin dashboard, but you can edit the message in `/wp-content/plugins/razorpay-quick-payments/razorpay-quick-payments.php` file. Please feel free to contact us if you have any doubts regarding the same.
