### ISSUE TITLE
Could not resolve host: api.razorpay.com

### ISSUE THREAD

**Issue by abhishektailor42** [razorpay/razorpay-quick-payments#22]
An uncaught Exception was encountered
Type: Requests_Exception

Message: cURL error 6: Could not resolve host: api.razorpay.com

Filename: /home/a2zroomz/public_html/testing/rppayment/libs/Requests-1.6.1/library/Requests/Transport/cURL.php

Please help to resolve error

**Comment by rgbufferchime** [comment]
same issue with me

**Comment by rgbufferchime** [comment]
@abhishektailor42 did u get any solution

**Comment by abhishektailor42** [comment]
No i didn't got any solutions 
did you get?

**Comment by abhishektailor42** [comment]
@rgbufferchime did you get any solution?

**Comment by ramth05** [comment]
We are working on fix and will release new version by early next week.

**Comment by ramth05** [comment]
@abhishektailor42 , are you able to access "https://api.razorpay.com/" from your server, where your site is running. if not please check the port 443 is open.

**Comment by abhishektailor42** [comment]
@ramth05 sir i have godaddy shared hosting and they said it's not possible in this plan so now what can i do? Please suggest sir

**Comment by ramth05** [comment]
@abhishektailor42 , I am not sure, but this is basic need to to access any API. Please upgrade your plan and ask them to allow the access.

**Comment by rgbufferchime** [comment]
how can we check 

> @abhishektailor42 , are you able to access "https://api.razorpay.com/" from your server, where your site is running. if not please check the port 443 is open.

how can we check if its accessing or not

**Comment by rgbufferchime** [comment]
i get a message welcome to razorpay on this

**Comment by abhishekdarteweb** [comment]
@ramth05 @rgbufferchime i also get a message {"message":"Welcome to Razorpay API."}

**Comment by rgbufferchime** [comment]
yes but it still shows curl error 6 in checkout

**Comment by sourav16** [comment]
same issue , only in godaddy shared hosting and support say all working fine

**Comment by ChetanGN** [comment]
Possible that this is happening due to a TLS version issue? You won't be able to make requests if you're still using TLS 1.0. More details here: https://razorpay.com/docs/announcements/tls/

**Comment by Lionelxki** [comment]
I think i have a solution

**Comment by bhagchandani** [comment]
Hi,
Did anyone find the solution? I get this error sometimes.

**Comment by akanshutambi811** [comment]
Did anyone find the solution?
