### ISSUE TITLE
error in upi scan on website http://excelinexcel.co.in/

### ISSUE THREAD

**Issue by deepakpant91** [razorpay/razorpay-quick-payments#24]
My website is in wocommerce and i am using razorpay plugin for store payments.All payments are working but on upi scan payment is successful but not redirecting to thank you page.

**Comment by ChetanGN** [comment]
@deepakpant91 we are not able to regenerate this issue, as it is working fine for all other customers. Kindly feel free to contact us if you are still facing this issue.
