### ISSUE TITLE
Disable button after first click

### ISSUE THREAD

**Issue by captn3m0** [razorpay/razorpay-quick-payments#3]
Since it takes time to hit the Razorpay servers and generate an order, the opening of iframe takes some time. We should disable the button while this is in progress (same as on woocommerce)

**Comment by siddhesh** [comment]
This is already done with #5.

**Comment by mayankamencherla** [comment]
@captn3m0 Close the issue?

**Comment by ChetanGN** [comment]
Already implemented this feature.
