### ISSUE TITLE
Razor Pay short code or using razor pay without woocomerce plugin in wordpress

### ISSUE THREAD

**Issue by vedavyasg507** [razorpay/razorpay-quick-payments#30]
Hi Team,

Can you please suggest an alternative to install Razorpay plugin into wordpress without installing woocommerce plugin and integrating a quick booking option.
Please do the needful.

Thanks,
G.Vedavyas

**Comment by ChetanGN** [comment]
Hi, @vedavyasg507.  We had released the [1.2.0](https://github.com/razorpay/razorpay-quick-payments/releases/tag/1.2.0) version. There is no dependency on the woocommerce plugin. You can install the razorpay quick payment plugin independently.

**Comment by ChetanGN** [comment]
@vedavyasg507 may I know the status of this issue?

**Comment by vedavyasg507** [comment]
The updates have solved the issue.
Thank you for the quick response.
I could not respond as I could not look into the issue. Now everything is
working fine.

Thank you very much.
